# Global allow list
[allowlist]
    regexes = ['''linkedin''']
    description = "Allowlisted files"
    files = ['''^\.?gitleaks.toml$''', '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$''', '''(go.mod|go.sum)$''']

# Rule specific white listing
[[rules]]
    id = "1"
    [rules.allowlist]
        regexes = ['''AKIAIO5FODNN7EXAMPLE.*''']

[[rules]]
    id = "3"
    [rules.allowlist]
        regexes = ['''3AKIAIO5FODNN7EXAMPLE.*''']
        description = "ignore example aws key"
