title = "gitleaks config"

[[rules]]
    description = "Rule 1: AWS Access Key"
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["key", "AWS"]

[[rules]]
    description = "Rule 2: AWS Secret Key"
    regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
    tags = ["key", "AWS"]

[[rules]]
    description = "Rule 3: AWS MWS key"
    regex = '''amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
    tags = ["key", "AWS", "MWS"]

[[rules]]
    description = "Rule 4: Facebook Secret Key"
    regex = '''(?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}['\"]'''
    tags = ["key", "Facebook"]

[[rules]]
    description = "Rule 5: Facebook Client ID"
    regex = '''(?i)(facebook|fb)(.{0,20})?['\"][0-9]{13,17}['\"]'''
    tags = ["key", "Facebook"]

[[rules]]
    description = "Rule 6: Twitter Secret Key"
    regex = '''(?i)twitter(.{0,20})?['\"][0-9a-z]{35,44}['\"]'''
    tags = ["key", "Twitter"]

[[rules]]
    description = "Rule 7: Twitter Client ID"
    regex = '''(?i)twitter(.{0,20})?['\"][0-9a-z]{18,25}['\"]'''
    tags = ["client", "Twitter"]

[[rules]]
    description = "Rule 8: Github Personal Access Token"
    regex = '''ghp_[0-9a-zA-Z]{36}'''
    tags = ["key", "Github"]
[[rules]]
    description = "Rule 9: Github OAuth Access Token"
    regex = '''gho_[0-9a-zA-Z]{36}'''
    tags = ["key", "Github"]
[[rules]]
    description = "Rule 10: Github App Token"
    regex = '''(ghu|ghs)_[0-9a-zA-Z]{36}'''
    tags = ["key", "Github"]
[[rules]]
    description = "Rule 11: Github Refresh Token"
    regex = '''ghr_[0-9a-zA-Z]{76}'''
    tags = ["key", "Github"]

[[rules]]
    description = "Rule 12: LinkedIn Client ID"
    regex = '''(?i)linkedin(.{0,20})?(?-i)[0-9a-z]{12}'''
    tags = ["client", "LinkedIn"]

[[rules]]
    description = "Rule 13: LinkedIn Secret Key"
    regex = '''(?i)linkedin(.{0,20})?[0-9a-z]{16}'''
    tags = ["secret", "LinkedIn"]

[[rules]]
    description = "Rule 14: Slack"
    regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
    tags = ["key", "Slack"]

[[rules]]
    description = "Rule 15: Asymmetric Private Key"
    regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
    tags = ["key", "AsymmetricPrivateKey"]

[[rules]]
    description = "Rule 16: Google API key"
    regex = '''AIza[0-9A-Za-z\\-_]{35}'''
    tags = ["key", "Google"]

[[rules]]
    description = "Rule 17: Google (GCP) Service Account"
    regex = '''"type": "service_account"'''
    tags = ["key", "Google"]

[[rules]]
    description = "Rule 18: Heroku API key"
    regex = '''(?i)heroku(.{0,20})?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
    tags = ["key", "Heroku"]

[[rules]]
    description = "Rule 19: MailChimp API key"
    regex = '''(?i)(mailchimp|mc)(.{0,20})?[0-9a-f]{32}-us[0-9]{1,2}'''
    tags = ["key", "Mailchimp"]

[[rules]]
    description = "Rule 20: Mailgun API key"
    regex = '''((?i)(mailgun|mg)(.{0,20})?)?key-[0-9a-z]{32}'''
    tags = ["key", "Mailgun"]

[[rules]]
    description = "Rule 21: PayPal Braintree access token"
    regex = '''access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}'''
    tags = ["key", "Paypal"]

[[rules]]
    description = "Rule 22: Picatic API key"
    regex = '''sk_live_[0-9a-z]{32}'''
    tags = ["key", "Picatic"]

[[rules]]
    description = "Rule 23: SendGrid API Key"
    regex = '''SG\.[\w_]{16,32}\.[\w_]{16,64}'''
    tags = ["key", "SendGrid"]

[[rules]]
    description = "Rule 24: Slack Webhook"
    regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8,12}/[a-zA-Z0-9_]{24}'''
    tags = ["key", "slack"]

[[rules]]
    description = "Rule 25: Stripe API key"
    regex = '''(?i)stripe(.{0,20})?[sr]k_live_[0-9a-zA-Z]{24}'''
    tags = ["key", "Stripe"]

[[rules]]
    description = "Rule 26: Square access token"
    regex = '''sq0atp-[0-9A-Za-z\-_]{22}'''
    tags = ["key", "square"]

[[rules]]
    description = "Rule 27: Square OAuth secret"
    regex = '''sq0csp-[0-9A-Za-z\\-_]{43}'''
    tags = ["key", "square"]

[[rules]]
    description = "Rule 28: Twilio API key"
    regex = '''(?i)twilio(.{0,20})?SK[0-9a-f]{32}'''
    tags = ["key", "twilio"]

[[rules]]
    description = "Rule 29: Dynatrace ttoken"
    regex = '''dt0[a-zA-Z]{1}[0-9]{2}\.[A-Z0-9]{24}\.[A-Z0-9]{64}'''
    tags = ["key", "Dynatrace"]

[[rules]]
    description = "Rule 30: Shopify shared secret"
    regex = '''shpss_[a-fA-F0-9]{32}'''
    tags = ["key", "Shopify"]

[[rules]]
    description = "Rule 31: Shopify access token"
    regex = '''shpat_[a-fA-F0-9]{32}'''
    tags = ["key", "Shopify"]

[[rules]]
    description = "Rule 32: Shopify custom app access token"
    regex = '''shpca_[a-fA-F0-9]{32}'''
    tags = ["key", "Shopify"]

[[rules]]
    description = "Rule 33: Shopify private app access token"
    regex = '''shppa_[a-fA-F0-9]{32}'''
    tags = ["key", "Shopify"]

[[rules]]
    description = "Rule 34: PyPI upload token"
    regex = '''pypi-AgEIcHlwaS5vcmc[A-Za-z0-9-_]{50,1000}'''
    tags = ["key", "pypi"]